<?php
// | Create: 2016/4/7 
// +----------------------------------------------------------------------
// | Author: 海枯 <haiku888@foxmail.com> 
// +----------------------------------------------------------------------
// | Description:  
// +----------------------------------------------------------------------

namespace Adminadd\Controller;


use Common\Controller\AdminbaseController;

class TopicController extends AdminbaseController
{
    protected $topicModel,$userModel;
    function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->topicModel = M('topic');
        $this->userModel = M('users');
    }

    /**
     * 后台验证tpl页面
     */
    public function topic_verify(){
        $where_ands=array("topic_status=0");
        $fields=array(
            'start_time'=> array("field"=>"topic_create","operator"=>">"),
            'end_time'  => array("field"=>"topic_create","operator"=>"<"),
            'keyword'  => array("field"=>"topic_title","operator"=>"like"),
        );
        if(IS_POST){

            foreach ($fields as $param =>$val){
                if (isset($_POST[$param]) && !empty($_POST[$param])) {
                    $operator=$val['operator'];
                    $field   =$val['field'];
                    $get=$_POST[$param];
                    $_GET[$param]=$get;
                    if($operator=="like"){
                        $get="%$get%";
                    }
                    array_push($where_ands, "$field $operator '$get'");
                }
            }
        }else{
            foreach ($fields as $param =>$val){
                if (isset($_GET[$param]) && !empty($_GET[$param])) {
                    $operator=$val['operator'];
                    $field   =$val['field'];
                    $get=$_GET[$param];
                    if($operator=="like"){
                        $get="%$get%";
                    }
                    array_push($where_ands, "$field $operator '$get'");
                }
            }
        }

        $where= join(" and ", $where_ands);

        $count=$this->topicModel
            ->alias("a")
            ->join(C('DB_PREFIX')."group as b ON a.group_id=b.group_id")
            ->join(C('DB_PREFIX')."users as c ON a.user_id=c.id")
            ->where($where)->count();
        $page = $this->page($count, 10);

        $posts=$this->topicModel
            ->alias("a")
            ->join(C('DB_PREFIX')."group as b ON a.group_id=b.group_id")
            ->join(C('DB_PREFIX')."users as c ON a.user_id=c.id")
            ->where($where)->limit($page->firstRow . ',' . $page->listRows)->select();

        $this->assign("Page", $page->show('Admin'));
        $this->assign("formget",$_GET);
        $this->assign("posts",$posts);

        $this->display(":topic_verify");
    }

    /**
     * topic内容页
     */
    function topic_content(){
        $id = I('id');
        $contt = $this->topicModel->where("topic_id=%d", $id)
            ->field('topic_content')->find();
        $this->assign("content", $contt);
        $this->display(":topic_content");
    }
    /**
     * 审核不通过操作
     */
    public function refuse(){
        if(isset($_POST['ids'])){
            $ids = implode(",", $_POST['ids']);
            $data=array("topic_status"=>"2");
            if ($this->topicModel->where("topic_id in ($ids)")->save($data)) {
                $this->success("拒绝成功！");
            } else {
                $this->error("拒绝失败！");
            }
        }else{
            if(isset($_GET['id'])){
                $id = intval(I("get.id"));
                $data=array("topic_id"=>$id,"topic_status"=>"2");
                if ($this->topicModel->save($data)) {
                    $this->success("拒绝成功！");
                } else {
                    $this->error("拒绝失败！");
                }
            }
        }
    }

    /**
     * 审核通过操作
     */
    public  function agree(){
        $groupModel =  M('group');
        if(isset($_POST['ids'])){
            $ids = implode(",", $_POST['ids']);
            $gids = [];
            foreach ($ids as $id) {
                $gid = $this->topicModel->where(array('topic_id'=>$id))->find()['group_id'];
                array_push($gids, $gid);
            }
            $groupModel->where("group_id in ($gids)")->setInc('chat_count');
            $data=array("topic_status"=>"1");
            if ($this->topicModel->where("topic_id in ($ids)")->save($data)) {
                $this->success("同意成功！");
            } else {
                $this->error("同意失败！");
            }
        }else{
            if(isset($_GET['id'])){
                $id = intval(I("get.id"));

                $gid = $this->topicModel->where(array('topic_id'=>$id))->find()['group_id'];

                $groupModel->where(array('group_id'=>$gid))->setInc('chat_count');
                $data=array("topic_id"=>$id,"topic_status"=>"1");
                if ($this->topicModel->save($data)) {
                    $this->success("同意成功！");
                } else {
                    $this->error("同意失败！");
                }
            }
        }
    }

    /**
     * 话题管理tpl
     */
    public function topicManage()
    {
        $uid = get_current_admin_id();
        if ($uid == 1) {
            $where_ands=[];
        }else{
            $where_ands = array("a.user_id=$uid");
        }
        $fields=array(
            'start_time'=> array("field"=>"topic_create","operator"=>">"),
            'end_time'  => array("field"=>"topic_create","operator"=>"<"),
            'keyword'  => array("field"=>"topic_title","operator"=>"like"),
            'sort'  => array("field"=>"topic_status","operator"=>"="),
        );
        if(IS_POST){

            foreach ($fields as $param =>$val){
                if (isset($_POST[$param]) && !empty($_POST[$param])) {
                    $operator=$val['operator'];
                    $field = $val['field'];
                    if ($param == 'start_time' || $param == 'end_time') {
                        $get = strtotime($_POST[$param]);
                    }else{
                        $get=$_POST[$param];
                    }

                    $_GET[$param]=$get;
                    if($operator=="like"){
                        $get="%$get%";
                    }
                    $where_ands = array("topic_status=1");
                    array_push($where_ands, "$field $operator '$get'");
                }
            }
        }else{
            foreach ($fields as $param =>$val){
                if (isset($_GET[$param]) && !empty($_GET[$param])) {

                    $operator=$val['operator'];
                    $field   =$val['field'];

                    if ($param == 'start_time' || $param == 'end_time') {
                        $get = strtotime($_GET[$param]);
                    }else{
                        $get=$_GET[$param];
                    }

                    if($operator=="like"){
                        $get="%$get%";
                    }
                    array_push($where_ands, "$field $operator '$get'");
                }else if($param=='sort'){
                    array_push($where_ands, "topic_status = '1'");
                }
            }
        }

        $where= join(" and ", $where_ands);
        $joinGroup = C('DB_PREFIX')."group as b ON a.group_id=b.group_id";
        $joinUser = C('DB_PREFIX') . "users as c ON a.user_id=c.id";
        $count=$this->topicModel->alias("a")
            ->join($joinGroup)
            ->join($joinUser)
            ->where($where)->count();
        $page = $this->page($count, 10);

        $posts=$this->topicModel->alias("a")
            ->join($joinGroup)
            ->join($joinUser)
            ->where($where)->limit($page->firstRow . ',' . $page->listRows)->select();
        $this->assign("Page", $page->show('Admin'));
        $this->assign("formget",$_GET);
        $this->assign("posts",NullTopicCover($posts));
        $this->display(':topicManage');
    }

    /**
     * 冻结用后ajax
     */
    public function freezeUser()
    {
        if(isset($_POST['ids'])){
            $ids = implode(",", $_POST['ids']);
            $data=array("user_status"=>"0");
            if ($this->userModel->where("id in ($ids)")->save($data)) {
                $this->success("封号成功！");
            } else {
                $this->error("封号失败！");
            }
        }else{
            if(isset($_GET['id'])){
                $id = intval(I("get.id"));
                $data=array("id"=>$id,"user_status"=>"0");
                if ($this->userModel->save($data)) {
                    $this->success("封号成功！");
                } else {
                    $this->error("封号失败！");
                }
            }
        }
    }

    /**
     * 删除话题ajax
     */
    public function deleteTopic()
    {
        if(isset($_POST['ids'])){
            $ids = implode(",", $_POST['ids']);
            $data=array("topic_status"=>"3");
            if ($this->topicModel->where("topic_id in ($ids)")->save($data)) {
                $this->success("删除话题成功！");
            } else {
                $this->error("删除话题失败！");
            }
        }else{
            if(isset($_GET['id'])){
                $id = intval(I("get.id"));
                $data=array("topic_id"=>$id,"topic_status"=>"3");
                if ($this->topicModel->save($data)) {
                    $this->success("删除话题成功！");
                } else {
                    $this->error("删除话题失败！");
                }
            }
        }
    }

    public function returnDeleteTopic()
    {
        if(isset($_POST['ids'])){
            $ids = implode(",", $_POST['ids']);
            $data=array("topic_status"=>"1");
            if ($this->topicModel->where("topic_id in ($ids)")->save($data)) {
                $this->success("撤出话题成功！");
            } else {
                $this->error("撤出话题失败！");
            }
        }else{
            if(isset($_GET['id'])){
                $id = intval(I("get.id"));
                $data=array("topic_id"=>$id,"topic_status"=>"1");
                if ($this->topicModel->save($data)) {
                    $this->success("撤出话题成功！");
                } else {
                    $this->error("撤出话题失败！");
                }
            }
        }
    }
}