<?php
// | Create: 2016/4/7 
// +----------------------------------------------------------------------
// | Author: 海枯 <haiku888@foxmail.com> 
// +----------------------------------------------------------------------
// | Description:  
// +----------------------------------------------------------------------

namespace Adminadd\Controller;


use Common\Controller\AdminbaseController;

class TopicController extends AdminbaseController
{
    protected $topicModel;
    function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->topicModel = M('topic');
    }

    /**
     * 后台验证tpl页面
     */
    public function topic_verify(){
        $where_ands=array("topic_status=0");
        $fields=array(
            'start_time'=> array("field"=>"topic_create","operator"=>">"),
            'end_time'  => array("field"=>"topic_create","operator"=>"<"),
            'keyword'  => array("field"=>"topic_title","operator"=>"like"),
        );
        if(IS_POST){

            foreach ($fields as $param =>$val){
                if (isset($_POST[$param]) && !empty($_POST[$param])) {
                    $operator=$val['operator'];
                    $field   =$val['field'];
                    $get=$_POST[$param];
                    $_GET[$param]=$get;
                    if($operator=="like"){
                        $get="%$get%";
                    }
                    array_push($where_ands, "$field $operator '$get'");
                }
            }
        }else{
            foreach ($fields as $param =>$val){
                if (isset($_GET[$param]) && !empty($_GET[$param])) {
                    $operator=$val['operator'];
                    $field   =$val['field'];
                    $get=$_GET[$param];
                    if($operator=="like"){
                        $get="%$get%";
                    }
                    array_push($where_ands, "$field $operator '$get'");
                }
            }
        }

        $where= join(" and ", $where_ands);

        $count=$this->topicModel
            ->alias("a")
            ->join(C('DB_PREFIX')."group as b ON a.group_id=b.group_id")
            ->join(C('DB_PREFIX')."users as c ON a.user_id=c.id")
            ->where($where)->count();
        $page = $this->page($count, 10);

        $posts=$this->topicModel
            ->alias("a")
            ->join(C('DB_PREFIX')."group as b ON a.group_id=b.group_id")
            ->join(C('DB_PREFIX')."users as c ON a.user_id=c.id")
            ->where($where)->limit($page->firstRow . ',' . $page->listRows)->select();

        $this->assign("Page", $page->show('Admin'));
        $this->assign("formget",$_GET);
        $this->assign("posts",$posts);

        $this->display(":topic_verify");
    }

    /**
     * topic内容页
     */
    function topic_content(){
        $id = I('id');
        $contt = $this->topicModel->where("topic_id=%d", $id)
            ->field('topic_content')->find();
        $this->assign("content", $contt);
        $this->display(":topic_content");
    }
    /**
     * 审核不通过操作
     */
    public function refuse(){
        if(isset($_POST['ids'])){
            $ids = implode(",", $_POST['ids']);
            $data=array("topic_status"=>"2");
            if ($this->topicModel->where("topic_id in ($ids)")->save($data)) {
                $this->success("拒绝成功！");
            } else {
                $this->error("拒绝失败！");
            }
        }else{
            if(isset($_GET['id'])){
                $id = intval(I("get.id"));
                $data=array("topic_id"=>$id,"topic_status"=>"2");
                if ($this->topicModel->save($data)) {
                    $this->success("拒绝成功！");
                } else {
                    $this->error("拒绝失败！");
                }
            }
        }
    }

    /**
     * 审核通过操作
     */
    public  function agree(){
        if(isset($_POST['ids'])){
            $ids = implode(",", $_POST['ids']);
            $data=array("topic_status"=>"1");
            if ($this->topicModel->where("topic_id in ($ids)")->save($data)) {
                $this->success("同意成功！");
            } else {
                $this->error("同意失败！");
            }
        }else{
            if(isset($_GET['id'])){
                $id = intval(I("get.id"));
                $data=array("topic_id"=>$id,"topic_status"=>"1");
                if ($this->topicModel->save($data)) {
                    $this->success("同意成功！");
                } else {
                    $this->error("同意失败！");
                }
            }
        }
    }
}