<?php
return array (
  'app' => 'Adminadd',
  'model' => 'Topic',
  'action' => 'x',
  'data' => '',
  'type' => '0',
  'status' => '1',
  'name' => '组织用户管理',
  'icon' => 'th',
  'remark' => '',
  'listorder' => '0',
  'children' => 
  array (
    array (
      'app' => 'Adminadd',
      'model' => 'Org',
      'action' => 'org_verify',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '组织用户审核',
      'icon' => '',
      'remark' => '组织用户注册审核',
      'listorder' => '0',
    ),
    array (
      'app' => 'Adminadd',
      'model' => 'Topic',
      'action' => 'topic_verify',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '话题审核',
      'icon' => 'fa-navicon',
      'remark' => '',
      'listorder' => '0',
    ),
    array (
      'app' => 'Adminadd',
      'model' => 'group',
      'action' => 'group_verify',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '小组申请审核',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
    ),
    array (
      'app' => 'protal',
      'model' => 'topic',
      'action' => 'topicadd',
      'data' => '',
      'type' => '1',
      'status' => '0',
      'name' => '话题添加',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
    ),
    array (
      'app' => 'Adminadd',
      'model' => 'activity',
      'action' => 'sign_check',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '活动报名信息审核',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
    ),
  ),
);