<?php
namespace Portal\Controller;
use Common\Controller\HomebaseController;

class groupController extends HomebaseController{
    protected $groupModel,$topicModel;
    function _initialize()
    {
        $this->groupModel = M('group');
        $this->topicModel = M('topic');
        parent::_initialize(); // TODO: Change the autogenerated stub
    }
    /*
     * 小组首页模板
     */
    function group(){
        $group = $this->groupModel->order('group_id desc')
            ->where('group_status=%d',1)->field("group_name,group_total,group_cover")->select();

        echo json_encode($group);
        $this->assign('group',$group);
        $this->display(":group");
    }

    /**
     * 小组详情页模板
     */
    function group_detail(){
        $id = intval(I('group_id'));
        $type = I('order');
        $this->getTopicMsg($id,$type);
        if(empty($id)){
            $this->error("参数错误");
        }else{
            $group = $this->groupModel->where("group_id=%d",$id)->find();
            if(empty($group)){
                $this->error('参数错误');
            }else{

                $this->NullPic($group);
            }
        }
        $this->display(":group_detail");
    }

    /**当封面为空时，用默认pic
     * @param $arr 查询结果
     */
    protected function NullPic($arr){

        foreach ($arr as $key => $item) {
            if($key=="group_cover" && empty($item)){
                $arr[$key]=sp_get_asset_upload_path("cover/default_tupian4.png");
            }
        }
        $this->assign('groupMes',$arr);
    }
    /**取得topic详情信息
     * @param $id
     * @param $type
     */
    protected function getTopicMsg($id,$type){
        if (empty($type)) {
            $msg = $this->groupModel->alias('a')
                ->join(C('DB_PREFIX')."topic b ON a.group_id = b.group_id")
                ->join(C('DB_PREFIX')."users c ON b.user_id = c.id")
                ->where("a.group_id=%d and b.topic_status=%d",$id,1)
                ->select();
        }else if($type=="lately"){      //最近话题
            $msg = $this->groupModel->alias('a')
                ->join(C('DB_PREFIX')."topic b ON a.group_id = b.group_id")
                ->join(C('DB_PREFIX')."users c ON b.user_id = c.id")
                ->where("a.group_id=%d and b.topic_status=%d",$id,1)
                ->order('b.topic_id DESC')
                ->select();

        }else if ($type == "hot") {     //最热话题`

        }
        $this->assign('topicMsg',$msg);
    }

    /**
     * 小组新增模板渲染
     */
    function group_add(){
        if (!sp_auth_check(sp_get_current_userid(), "portal/group/group_add")) {
            $this->error('只有组织用户才能创建小组');
        }
        $this->display(":group_add");
    }

    /**
     * ajax小组增加
     */
    function do_group_add(){
        $GroupModel =  D('group');
        if (!sp_auth_check(sp_get_current_userid(), "portal/group/group_add")) {
            $this->error('只有组织用户才能创建小组');
        }else if(!sp_check_verify_code()){
            $this->error('验证码错误，请重新输入');
        }else{
            if (!$GroupModel->create()) {
                $this->error($GroupModel->getError());
            }else{
                $GroupModel->add();
                $this->success('新增小组成功，请等待管理员审核',U('group'));
            }
        }
    }
}