<?php
namespace Portal\Controller;

use Common\Controller\MemberbaseController;

class TopicController extends MemberbaseController{
    protected $topicModel,$groupModel;
    function _initialize()
    {
        $this->topicModel = D('Portal/Topic');
        $this->groupModel = M('group');
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    function topic(){
        $this->display(":topic");
    }

    /**
     * 话题增加页
     */
    function topicadd(){
        if(!sp_auth_check(sp_get_current_userid(),'portal/topic/topicadd')){
            $this->error('你不是组织用户没有访问权限');
        }
        $this->display(":topicadd");
    }

    /**
     * 话题增加ajax
     */
    function dotopicadd(){
        $id = I('group_id');
        if(!sp_auth_check(sp_get_current_userid(),'portal/topic/topicadd')){
            $this->error('你不是组织用户没有访问权限');
        }else if($this->judgeId($id)==0){
            $this->error('参数错误，不存在该小组');
        }else if(!sp_check_verify_code()){
            $this->error("验证码错误请重新输入");
        }else{
//            var_dump($this->topicModel);
            //不合法
            $createRsg = $this->topicModel->create();
            $group_id = I('group_id');
            if(!$createRsg)
            {
                $this->error($this->topicModel->getError());
            }else if($this->topicModel->add()){
                $this->success('话题新增成功，请等待管理员审核',U('Portal/group/group_detail',array('group_id'=>$group_id)));
            }else{
                $this->error('话题新增失败，具体原因请联系管理员');
            }
        }
    }

    /**判断group_id参数是否非法
     * @param $id   get参数
     * @return mixed 小组的数量 0表示没有改小组
     */
    function judgeId($id){
        $num = $this->groupModel->where('group_id=%d',$id)
            ->count();
        return $num;
    }
}